name: Quality Gates

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate-plan:
    name: Validate modernization plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate diagnostics against plan
        run: |
          python scripts/validate_plan.py

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    needs: validate-plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SBOM tooling
        run: pip install cyclonedx-bom

      - name: Generate CycloneDX SBOM
        run: |
          cyclonedx-py requirements \
            --requirements requirements.txt \
            --output sbom.json \
            --format json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
          if-no-files-found: error
