 name: A2A Research Workflow

 on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
   workflow_dispatch:
-  schedule:
-    - cron: "0 8-20 * * 1-5"
-      timezone: "Europe/Berlin"
-      # Montag bis Freitag zwischen 08:00 und 20:00 Uhr CET, stündlich
+  # Achtung: GitHub Actions nutzt UTC (keine timezone-Unterstützung).
+  # Diese Cron deckt ca. 07–19 CET / 06–18 CEST ab (Mo–Fr, stündlich).
+  schedule:
+    - cron: "0 6-18 * * 1-5"

 jobs:
   build-and-test:
@@
   run-orchestrator:
@@
       # Prüft, dass alle benötigten Secrets vorhanden sind
       - name: Preflight env check
         env:
-          GOOGLE_CLIENT_ID_V2:     ${{ secrets.GOOGLE_CLIENT_ID_V2 }}
-          GOOGLE_CLIENT_SECRET_V2: ${{ secrets.GOOGLE_CLIENT_SECRET_V2 }}
-          GOOGLE_REFRESH_TOKEN:    ${{ secrets.GOOGLE_REFRESH_TOKEN }}
+          GOOGLE_CLIENT_ID:        ${{ secrets.GOOGLE_CLIENT_ID }}
+          GOOGLE_CLIENT_SECRET:    ${{ secrets.GOOGLE_CLIENT_SECRET }}
+          GOOGLE_REFRESH_TOKEN:    ${{ secrets.GOOGLE_REFRESH_TOKEN }}
+          HUBSPOT_ACCESS_TOKEN:    ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
+          HUBSPOT_PORTAL_ID:       ${{ secrets.HUBSPOT_PORTAL_ID }}
+          SMTP_HOST:               ${{ secrets.SMTP_HOST }}
+          SMTP_PORT:               ${{ secrets.SMTP_PORT }}
+          MAIL_FROM:               ${{ secrets.MAIL_FROM }}
         run: |
           set -e
-          for v in GOOGLE_CLIENT_ID_V2 GOOGLE_CLIENT_SECRET_V2 GOOGLE_REFRESH_TOKEN; do
+          for v in GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET GOOGLE_REFRESH_TOKEN HUBSPOT_ACCESS_TOKEN HUBSPOT_PORTAL_ID SMTP_HOST SMTP_PORT MAIL_FROM; do
             if [ -z "${!v}" ]; then
               echo "::error::Missing required env $v"
               exit 1
             else
               echo "$v=✓"
             fi
           done

       - name: Run orchestrator
         env:
           PYTHONPATH:               ${{ env.PYTHONPATH }}
-          GOOGLE_CLIENT_ID_V2:      ${{ secrets.GOOGLE_CLIENT_ID_V2 }}
-          GOOGLE_CLIENT_SECRET_V2:  ${{ secrets.GOOGLE_CLIENT_SECRET_V2 }}
+          GOOGLE_CLIENT_ID:         ${{ secrets.GOOGLE_CLIENT_ID }}
+          GOOGLE_CLIENT_SECRET:     ${{ secrets.GOOGLE_CLIENT_SECRET }}
           GOOGLE_REFRESH_TOKEN:     ${{ secrets.GOOGLE_REFRESH_TOKEN }}
           HUBSPOT_ACCESS_TOKEN:     ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
-          EMAIL_SMTP_HOST:          ${{ secrets.EMAIL_SMTP_HOST }}
-          EMAIL_SMTP_USER:          ${{ secrets.EMAIL_SMTP_USER }}
-          EMAIL_SMTP_PASS:          ${{ secrets.EMAIL_SMTP_PASS }}
+          HUBSPOT_PORTAL_ID:        ${{ secrets.HUBSPOT_PORTAL_ID }}
+          SMTP_HOST:                ${{ secrets.SMTP_HOST }}
+          SMTP_PORT:                ${{ secrets.SMTP_PORT }}
+          SMTP_USER:                ${{ secrets.SMTP_USER }}
+          SMTP_PASS:                ${{ secrets.SMTP_PASS }}
+          SMTP_SECURE:              ${{ secrets.SMTP_SECURE }}
+          MAIL_FROM:                ${{ secrets.MAIL_FROM }}
         run: |
           set -e
           if [ -f scripts/a2a_run.py ]; then
             python scripts/a2a_run.py
           elif [ -f a2a_run.py ]; then
             python a2a_run.py
           else
             file=$(find . -type f -name "*orchestrator*.py" | head -n1)
             if [ -n "$file" ]; then
               python "$file"
             else
               echo "No entrypoint found"
               exit 1
             fi
           fi
