name: A2A Research Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  # Achtung: GitHub Actions nutzt UTC. Diese Cron deckt ca. 07–19 CET / 06–18 CEST ab (Mo–Fr, stündlich).
  schedule:
    - cron: "0 6-18 * * 1-5"

permissions:
  contents: read

concurrency:
  group: a2a-research-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest

  run-orchestrator:
    runs-on: ubuntu-latest
    needs: build-and-test
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Preflight env check
        env:
          GOOGLE_CLIENT_ID:        ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET:    ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN:    ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          HUBSPOT_ACCESS_TOKEN:    ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
          HUBSPOT_PORTAL_ID:       ${{ secrets.HUBSPOT_PORTAL_ID }}
          SMTP_HOST:               ${{ secrets.SMTP_HOST }}
          SMTP_PORT:               ${{ secrets.SMTP_PORT }}
          MAIL_FROM:               ${{ secrets.MAIL_FROM }}
        run: |
          set -e
          for v in GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET GOOGLE_REFRESH_TOKEN HUBSPOT_ACCESS_TOKEN HUBSPOT_PORTAL_ID SMTP_HOST SMTP_PORT MAIL_FROM; do
            if [ -z "${!v}" ]; then
              echo "::error::Missing required env $v"
              exit 1
            else
              echo "$v=✓"
            fi
          done

      - name: Run orchestrator
        env:
          PYTHONPATH:               ${{ env.PYTHONPATH }}
          GOOGLE_CLIENT_ID:         ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET:     ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN:     ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          HUBSPOT_ACCESS_TOKEN:     ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
          HUBSPOT_PORTAL_ID:        ${{ secrets.HUBSPOT_PORTAL_ID }}
          SMTP_HOST:                ${{ secrets.SMTP_HOST }}
          SMTP_PORT:                ${{ secrets.SMTP_PORT }}
          SMTP_USER:                ${{ secrets.SMTP_USER }}
          SMTP_PASS:                ${{ secrets.SMTP_PASS }}
          SMTP_SECURE:              ${{ secrets.SMTP_SECURE }}
          MAIL_FROM:                ${{ secrets.MAIL_FROM }}
        run: |
          set -e
          if [ -f scripts/a2a_run.py ]; then
            python scripts/a2a_run.py
          elif [ -f a2a_run.py ]; then
            python a2a_run.py
          else
            file=$(find . -type f -name "*orchestrator*.py" | head -n1)
            if [ -n "$file" ]; then
              python "$file"
            else
              echo "No entrypoint found"
              exit 1
            fi
          fi

      - name: Upload outputs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            output/**
            **/*.pdf
          if-no-files-found: ignore
