 name: CI
@@
 jobs:
   build:
     runs-on: ubuntu-latest
     timeout-minutes: 15
+    env:
+      # stabile Defaults für Unit-Tests (keine echten Außenbindungen)
+      TRIGGER_WORDS_FILE: tests/fixtures/triggers.txt
+      SMTP_HOST: localhost
+      SMTP_PORT: 2525
+      MAIL_FROM: ci@example.test
@@
       - name: Run tests
-        run: pytest
+        run: pytest -q
