 name: CI
@@
   build:
     runs-on: ubuntu-latest
     timeout-minutes: 15
     env:
-      # Stable defaults for unit tests (no real external connections)
-      TRIGGER_WORDS_FILE: tests/fixtures/triggers.txt
-      SMTP_HOST: localhost
-      SMTP_PORT: 2525
-      MAIL_FROM: ci@example.test
+      # Stable defaults for unit tests (no real external connections)
+      TRIGGER_WORDS_FILE: tests/fixtures/triggers.txt
+      SMTP_HOST: localhost
+      SMTP_PORT: 2525
+      MAIL_FROM: ci@example.test
     steps:
@@
-      - name: Run tests
-        run: |
-          python -m pytest \
-            tests/test_calendar_fetch.py \
-            tests/test_ci_cd_workflow_yaml.py \
-            tests/test_orchestrator.py \
-            tests/test_utils.py -q
+      - name: Run tests
+        env:
+          # Force TEST mode (applied in settings.py: lookback=1, lookahead=14, live_mode=0)
+          A2A_TEST_MODE: "1"
+          LIVE_MODE: "0"
+          # Do NOT set CAL_* in CI; if they exist in repo/org settings, TEST mode ignores them
+        run: |
+          python -m pytest \
+            tests/test_calendar_fetch.py \
+            tests/test_ci_cd_workflow_yaml.py \
+            tests/test_orchestrator.py \
+            tests/test_utils.py -q
