name: live-e2e

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TEST_COMPANY_NAME: ACME Sandbox GmbH
      TEST_COMPANY_DOMAIN: acme.example
      TEST_CREATOR_EMAIL: konstantin@yourdomain.tld
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: pip install -r requirements.txt
      - name: Run internal search
        env:
          HUBSPOT_ACCESS_TOKEN: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
          HUBSPOT_PORTAL_ID: ${{ secrets.HUBSPOT_PORTAL_ID }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
        run: |
          python - <<'PY'
          import os, json
          from agents.agent_internal_search import run

          payload = {
              'company_name': os.environ['TEST_COMPANY_NAME'],
              'company_domain': os.environ['TEST_COMPANY_DOMAIN'],
              'creator_email': os.environ['TEST_CREATOR_EMAIL'],
          }
          res = run({'payload': payload})
          print(json.dumps(res))
          assert res['payload']['action'] in {'NOT_IN_CRM','AWAIT_REQUESTOR_DECISION','NEEDS_DETAIL_RESEARCH','DELIVERED_EXISTING'}
          PY
