name: SMTP Self-Test

on:
  workflow_dispatch:
    inputs:
      recipient:
        description: "Empfänger-Adresse"
        required: true
        default: "kontakt@konstantinmilonas.de"
      subject:
        description: "Betreff"
        required: false
        default: "SMTP self-test (GitHub Actions)"
      body:
        description: "Nachricht"
        required: false
        default: "✅ SMTP works — sent via A2A workflow."

jobs:
  send:
    runs-on: ubuntu-latest
    env:
      SMTP_HOST:   ${{ secrets.SMTP_HOST }}
      SMTP_PORT:   ${{ secrets.SMTP_PORT }}
      SMTP_USER:   ${{ secrets.SMTP_USER }}
      SMTP_PASS:   ${{ secrets.SMTP_PASS }}
      SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
      SMTP_FROM:   ${{ secrets.MAIL_FROM }}
      MAIL_FROM:   ${{ secrets.MAIL_FROM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Send test mail
        run: |
          python - <<'PY'
          from integrations.email_sender import send_email
          send_email(
              "${{ github.event.inputs.recipient }}",
              "${{ github.event.inputs.subject }}",
              "${{ github.event.inputs.body }}"
          )
          print("✅ Mail versendet an:", "${{ github.event.inputs.recipient }}")
          PY
